### ISSUE TITLE
Error with findNLDI function - not recognizing any downstream distance

### ISSUE THREAD

**Issue by Aml-ICF** [internetofwater/nldi-services#315] opened 2022-07-06 19:57 UTC
I am having an issue with the findNLDI function that started on Tuesday 07/05/22. I could use the function without any issues before then.

 x_DM <- findNLDI(comid = 18563181,
                   nav = c("DM"))

I have tried different COMIDs, different "nav" parameters, and different "distance_km" values (including the default 100 km as shown above) and it results in the same error message.

"Error: Cannot open "<html>

An HTML representation is not available for this resource.
<br/>
If you would like to see the data as JSON, <a href="https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/18563181/navigation/DM/flowlines?f=json&distance=100">click here</a>.

</html>
"; The file doesn't seem to exist. "

I followed the link and I got the following message: "{"description":"getNavigationFlowlines.distance: distance must be between 1 and 9999 kilometers","type":"error"}"

As I mentioned above, I've tried several different distances (1, 100, 4000) and I receive the same error message. Any help would be appreciated, we're using this function in support of a few different analyses for EPA rulemakings.

**Comment by ksonda** [comment] 2022-07-06 20:03
It looks like [findNLDI()](https://github.com/USGS-R/dataRetrieval/blob/9969de4285d2d238893a4c3c96c2c8e2e73a6aa7/R/findNLDI.R) does not construct the request URL with "?f=json" and/or the NLDI is not returning JSON by default for the R httr requests

**Comment by Aml-ICF** [comment] 2022-07-06 20:55
I set an f= parameter (see below example) and I don't encounter the error anymore but it doesn't appear to be navigating downstream as expected. The following code only returns one observation in a data frame (likely because of the code at the end of the findNLDI() function that doesn't return lists for one length elements?)

x_DM <- findNLDI(comid = 18563181,
nav = c("DM"),
f = "html")

I've also tried other COMIDs and setting the distance_km value with the same result.

**Comment by ksonda** [comment] 2022-07-07 15:53
Here's a start

```
findNLDI_from_comid <- function(nav = c("UM", "UT", "DM", "DD"), 
                      distance=100,
                      comid,
                      source = "flowlines") {
  url = paste0("https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/",
               comid,
               "/navigation/",
               nav,
               "/",
               source,
               "?f=json&distance=",
               distance
               )
  x <- sf::read_sf(url)
    return(x)
}
```

Then you can do

```
 x <- findNLDI_from_comid(comid = 18563181, nav="DM", distance = 100)
```

**Comment by Aml-ICF** [comment] 2022-07-07 18:29
That worked, thanks for the help! 

I'll keep an eye out for updates to the dataRetrieval package.

**Comment by mikejohnson51** [comment] 2022-07-08 20:36
Hi all, 
`findNLDI` does not take an `f` parameter, and it was the change to defaulting to HTML pages that caused this request to fail. The URLs built in `findNLDI` (on my personal fork) are now explicitly constructed to return JSON.  I will work this into a PR for the `USGS-R/dataRetrieval` repo.

Hope it helps!

``` r
library(dataRetrieval)
findNLDI(comid = 18563181, nav = c("DM"))
#> $origin
#> Simple feature collection with 1 feature and 3 fields
#> Geometry type: LINESTRING
#> Dimension:     XY
#> Bounding box:  xmin: -86.58079 ymin: 34.04676 xmax: -86.57408 ymax: 34.05215
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 4
#>   sourceName    identifier comid                                        geometry
#>   <chr>         <chr>      <chr>                                <LINESTRING [°]>
#> 1 NHDPlus comid 18563181   18563181 (-86.58079 34.05215, -86.57956 34.05031, -8…
#> 
#> $DM_flowlines
#> Simple feature collection with 56 features and 1 field
#> Geometry type: LINESTRING
#> Dimension:     XY
#> Bounding box:  xmin: -86.92159 ymin: 33.73669 xmax: -86.55485 ymax: 34.05215
#> Geodetic CRS:  WGS 84
#> # A tibble: 56 × 2
#>    nhdplus_comid                                                        geometry
#>    <chr>                                                        <LINESTRING [°]>
#>  1 18563181      (-86.58079 34.05215, -86.57956 34.05031, -86.57934 34.04972, -…
#>  2 18563183                             (-86.57408 34.04676, -86.57378 34.04644)
#>  3 18563235      (-86.57378 34.04644, -86.57271 34.046, -86.57216 34.04527, -86…
#>  4 18563487      (-86.55485 34.03734, -86.5559 34.03424, -86.55728 34.03113, -8…
#>  5 18563333      (-86.58656 34.02102, -86.58656 34.02031, -86.5864 34.01976, -8…
#>  6 18563343      (-86.59091 34.0127, -86.59149 34.01204, -86.59185 34.01142, -8…
#>  7 18563357      (-86.59204 34.00867, -86.59207 34.00821, -86.59174 34.00764, -…
#>  8 18563373      (-86.59757 34.00398, -86.59787 34.00343, -86.5979 34.00256, -8…
#>  9 18563403      (-86.59757 34.00168, -86.59754 34.00155, -86.59724 34.00125, -…
#> 10 18564589      (-86.59729 34.00011, -86.59749 33.99964, -86.59823 33.99887, -…
#> # … with 46 more rows
```

<sup>Created on 2022-07-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by EthanGrahn** [comment] 2022-07-09 13:19
Adding `f=json` is a valid resolution for `findNLDI` although I may have discovered the root cause which could be adjusted in the NLDI services.

Sending a request with an `Accept` header as either `*/*` or `application/json` will return a valid result. Setting the header to multiple values (e.g. `application/json,text/xml,text/html,*/*`) will return the html page. Browsers often do some form of this.

This is due to a catch-all being added with the latest release to replicate legacy functionality where browsers will be shown an html page with a redirect link. The catch-all matches any `text/html` requests, while the data endpoints match `application/json` or associated types. I will create a new issue to figure out why it isn't favoring the first Accept value that is indicated.

**Comment by EthanGrahn** [comment] 2022-07-11 19:47
I've temporarily disabled html pages as a patch while I investigate a different approach. This should allow the original request to succeed.

**Comment by EthanGrahn** [comment] 2022-07-13 19:19
A new version of the NLDI services were deployed and have a fix for this header issue. These requests should now succeed as expected. I am going to close this issue, but if anybody is still running into issues related to this, please open a new issue with details and I will investigate further.

**Comment by dblodgett-usgs** [comment] 2022-07-14 13:57
Bypassing dataRetrieval for now, I see:

``` r
test <- httr::GET(
  paste0("https://labs.waterdata.usgs.gov/",
         "api/nldi/linked-data/nwissite/USGS-11120000/",
         "navigation/DM/flowlines?distance=100"))

test$request
#> <request>
#> GET https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-11120000/navigation/DM/flowlines?distance=100
#> Output: write_memory
#> Options:
#> * useragent: libcurl/7.64.1 r-curl/4.3.2 httr/1.4.3
#> * httpget: TRUE
#> Headers:
#> * Accept: application/json, text/xml, application/xml, */*

rawToChar(test$content)
#> [1] "<html>\n\nAn HTML representation is not available for this resource.\n<br/>\nIf you would like to see the data as JSON, <a href=\"https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-11120000/navigation/DM/flowlines?f=json&distance=100\">click here</a>.\n\n</html>\n"
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


Shouldn't the `Accept: application/json` be triggering the json media type rather than html?

**Comment by EthanGrahn** [comment] 2022-07-22 12:55
A new NLDI update was release on 7/18 which is expected to resolve this issue. If anyone is still having issues, please let us know. Otherwise, I will close this issue next week.

**Closed** 2022-07-25 14:05 UTC
